site_name: Machine Learning Notes
nav:
  - Home: 'index.md'
  - Data Analysis: 
    - 'The Six Phases of data Analysis': '00_DATA/README.md'
    - 'Dimensions of Data Analytics': '00_DATA/section_01.md'
    - 'Databases': 
      - 'Introduction': '00_DATA/section_02.md'
      - 'OpenTSDB': '00_DATA/databases/opentsdb.md'
      - 'Goku': '00_DATA/databases/goku.md'
    - Math: 
      - 'section 1': '05_MATH/section_01.md'
      - 'section 2': '05_MATH/section_02.md'
    - Workflows: '04_WORKFLOWS/section_01.md'
  - Machine Learning:
    - Supervised-Learning:
      - 'Introduction': '01_SUPERVISED_LEARNING/section_01.md'
      - 'Linear Regressions': '01_SUPERVISED_LEARNING/section_02.md'
      - 'Support Vector Machines': '01_SUPERVISED_LEARNING/section_03.md'
    - Unsupervised-Learning: '02_UNSUPERVISED_LEARNING/section_01.md'
  - Data Mining: '02_UNSUPERVISED_LEARNING/section_01.md'

plugins:
  - search
  - mermaid2
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - smarty
  - mdx_math